name: Clone

on:
  pull_request_target:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  Clone:
    # Don't run on forked repos.
    if: github.repository_owner == 'PaddlePaddle'
    runs-on: ubuntu-latest
    env:
      PR_ID: ${{ github.event.pull_request.number }}
      COMMIT_ID: ${{ github.event.pull_request.head.sha }}
      BRANCH: develop
    steps:
    - name: Clone paddle
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1000

    - name: Merge PR to test branch
      run: |
        git fetch origin pull/${PR_ID}/merge
        git checkout -b test FETCH_HEAD

    - name: Cache bos client
      id: cache_bos_client
      uses: actions/cache@v4
      with:
        path: |
          /home/runner/work/Paddle/bos_upload.py
          ~/.cache/pip
        key: bos_client_pip

    - name: Download bos client
      env:
        WORK: "/home/runner/work/Paddle"
      if: steps.cache_bos_client.outputs.cache-hit != 'true'
      run: |
        cd $WORK
        wget -q --no-proxy -O bos_upload.py  https://paddle-docker-tar.cdn.bcebos.com/bos_upload.py --no-check-certificate

    - name: Push paddle-action.tar.gz to bos
      env:
        WORK: "/home/runner/work/Paddle"
        AK: ${{ secrets.AK }}
        SK: ${{ secrets.SK }}
      run: |
        cd $WORK
        tar -zcf Paddle-action.tar.gz Paddle
        python -m pip install bce-python-sdk==0.8.74
        python bos_upload.py Paddle-action.tar.gz xly-devops/PR/Paddle/${PR_ID}/${COMMIT_ID}
